-- Re-key listening progress + practice answers to youtube_id (the key the mobile
-- app uses everywhere) instead of listening_id, and add SECURITY DEFINER write
-- RPCs that resolve the user from auth.uid() (mirroring save_recording), so the
-- client never has to send a user id and writes can't be spoofed. These tables
-- had no data yet, so DROP + recreate is safe.

-- ===================== VIDEO STEP PROGRESS =====================
DROP TABLE IF EXISTS "public"."listening_video_progress";

CREATE TABLE "public"."listening_video_progress" (
  "user_id"        bigint NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  "youtube_id"     text   NOT NULL,
  "step_key"       text   NOT NULL,
  "state"          int    NOT NULL DEFAULT 0,
  "open_count"     int    NOT NULL DEFAULT 0,
  "last_opened_at" timestamptz,
  "updated_at"     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "youtube_id", "step_key")
);
ALTER TABLE "public"."listening_video_progress" OWNER TO "postgres";
ALTER TABLE "public"."listening_video_progress" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own video progress" ON "public"."listening_video_progress"
  FOR ALL TO "authenticated"
  USING      ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()))
  WITH CHECK ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."listening_video_progress" TO "authenticated";
GRANT ALL ON "public"."listening_video_progress" TO "service_role";

CREATE OR REPLACE FUNCTION "public"."upsert_video_progress"(
    "p_youtube_id" text, "p_step_key" text, "p_state" int, "p_open_count" int
)
    RETURNS void LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user_id bigint;
BEGIN
  SELECT id INTO v_user_id FROM public.users WHERE user_id = auth.uid();
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'No user row for the current auth user'; END IF;
  INSERT INTO public.listening_video_progress
    (user_id, youtube_id, step_key, state, open_count, last_opened_at, updated_at)
  VALUES (v_user_id, p_youtube_id, p_step_key, p_state, p_open_count, now(), now())
  ON CONFLICT (user_id, youtube_id, step_key) DO UPDATE
    SET state = excluded.state,
        open_count = excluded.open_count,
        last_opened_at = now(),
        updated_at = now();
END; $$;
ALTER FUNCTION "public"."upsert_video_progress"(text, text, int, int) OWNER TO "postgres";
REVOKE ALL ON FUNCTION "public"."upsert_video_progress"(text, text, int, int) FROM PUBLIC, "anon";
GRANT EXECUTE ON FUNCTION "public"."upsert_video_progress"(text, text, int, int) TO "authenticated", "service_role";

-- ===================== PRACTICE ANSWERS (MCQ) =====================
DROP TABLE IF EXISTS "public"."listening_practice_answers";

CREATE TABLE "public"."listening_practice_answers" (
  "id"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"     bigint NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  "youtube_id"  text   NOT NULL,
  "group_id"    text   NOT NULL,
  "question_id" int    NOT NULL,
  "user_answer" text,
  "time_spent"  int    NOT NULL,
  "is_correct"  boolean NOT NULL,
  "created_at"  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "public"."listening_practice_answers" OWNER TO "postgres";
CREATE INDEX "lpa_user_video_idx" ON "public"."listening_practice_answers" ("user_id", "youtube_id");
ALTER TABLE "public"."listening_practice_answers" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own practice answers" ON "public"."listening_practice_answers"
  FOR ALL TO "authenticated"
  USING      ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()))
  WITH CHECK ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."listening_practice_answers" TO "authenticated";
GRANT ALL ON "public"."listening_practice_answers" TO "service_role";

CREATE OR REPLACE FUNCTION "public"."save_practice_answers"("p_youtube_id" text, "p_answers" jsonb)
    RETURNS void LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user_id bigint;
BEGIN
  SELECT id INTO v_user_id FROM public.users WHERE user_id = auth.uid();
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'No user row for the current auth user'; END IF;
  INSERT INTO public.listening_practice_answers
    (user_id, youtube_id, group_id, question_id, user_answer, time_spent, is_correct)
  SELECT v_user_id, p_youtube_id,
         a->>'group_id', (a->>'question_id')::int, a->>'user_answer',
         (a->>'time_spent')::int, (a->>'is_correct')::boolean
  FROM jsonb_array_elements(p_answers) AS a;
END; $$;
ALTER FUNCTION "public"."save_practice_answers"(text, jsonb) OWNER TO "postgres";
REVOKE ALL ON FUNCTION "public"."save_practice_answers"(text, jsonb) FROM PUBLIC, "anon";
GRANT EXECUTE ON FUNCTION "public"."save_practice_answers"(text, jsonb) TO "authenticated", "service_role";
