-- User-initiated premium payment + admin review queue (manual screenshot flow).
--
-- Builds ON TOP of the existing subscriptions system (20260607120000):
--   * users.premium_until stays the source of truth for premium access.
--   * grant_subscription() stays the ONLY thing that extends premium_until and
--     writes the subscriptions ledger. Approval here just CALLS it.
--
-- What's new:
--   1. payment_methods   — admin-managed pay destinations (KPay now, bank later)
--                          shown to the user: account number to copy + optional QR
--                          + the amount to pay. Each method sells one plan.
--   2. payment_submissions — the review inbox. A user uploads a receipt screenshot
--                          -> one 'pending' row. Admin approve -> grant_subscription
--                          + status 'approved'; reject -> reason + status 'rejected'.
--                          Users can read/insert their own; never update (no self-grant).
--   3. payment-proofs    — private storage bucket for the screenshots.
--   4. realtime          — publish users + payment_submissions so the mobile
--                          "pending" screen unlocks live the moment the admin approves.

-- ---------------------------------------------------------------------------
-- 1. Payment methods (admin-managed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."payment_methods" (
    "id"             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type"           text    NOT NULL,                       -- 'kpay' | 'wave' | 'bank' | ...
    "display_name"   text    NOT NULL,                       -- "KBZPay", "AYA Bank", ...
    "account_name"   text    NOT NULL,                       -- account holder name
    "account_number" text    NOT NULL,                       -- phone / account no to copy
    "qr_object_path" text,                                   -- optional QR image (payment-proofs/_qr/...)
    "instructions"   text,                                   -- free-text notes shown to the user
    "amount"         numeric NOT NULL,                       -- price the user pays via this method
    "currency"       text    NOT NULL DEFAULT 'MMK',
    "plan_code"      text    NOT NULL DEFAULT '12_month'     -- which plan this method sells (duration)
                     REFERENCES "public"."subscription_plans"("code") ON UPDATE CASCADE,
    "is_active"      boolean NOT NULL DEFAULT true,
    "sort_order"     integer NOT NULL DEFAULT 0,
    "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at"     timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."payment_methods" OWNER TO "postgres";

-- ---------------------------------------------------------------------------
-- 2. Payment submissions (review inbox / audit trail)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."payment_submissions" (
    "id"                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"           bigint NOT NULL
                        REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "payment_method_id" bigint
                        REFERENCES "public"."payment_methods"("id") ON UPDATE CASCADE ON DELETE SET NULL,
    -- snapshots: keep history stable even if the method is later edited/deleted.
    "method_label"      text    NOT NULL,
    "plan_code"         text    NOT NULL,
    "amount"            numeric NOT NULL,
    "currency"          text    NOT NULL DEFAULT 'MMK',
    "proof_path"        text    NOT NULL,                    -- payment-proofs/{auth.uid()}/{uuid}
    "status"            text    NOT NULL DEFAULT 'pending',  -- pending | approved | rejected
    "reject_reason"     text,
    "subscription_id"   bigint  REFERENCES "public"."subscriptions"("id") ON DELETE SET NULL,
    "reviewed_by"       uuid,                                -- admin auth.uid() when available
    "reviewed_at"       timestamp with time zone,
    "created_at"        timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."payment_submissions" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "payment_submissions_status_idx"
  ON "public"."payment_submissions" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "payment_submissions_user_idx"
  ON "public"."payment_submissions" ("user_id", "created_at" DESC);

-- One open request per user: blocks a second 'pending' submission while one is
-- already awaiting review (anti-dupe). Rejected/approved rows don't count, so a
-- user can always resubmit after a rejection.
CREATE UNIQUE INDEX IF NOT EXISTS "payment_submissions_one_pending_per_user"
  ON "public"."payment_submissions" ("user_id")
  WHERE "status" = 'pending';

-- ---------------------------------------------------------------------------
-- 3. Approve / reject RPCs (service_role only; SECURITY DEFINER).
--    Approval delegates the money math to the existing grant_subscription().
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."approve_payment_submission"("submission_id" bigint)
    RETURNS "public"."subscriptions"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET search_path = public
    AS $$
DECLARE
  v_sub_req public.payment_submissions;
  v_sub     public.subscriptions;
BEGIN
  SELECT * INTO v_sub_req
  FROM public.payment_submissions
  WHERE id = submission_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown submission: %', submission_id;
  END IF;
  IF v_sub_req.status <> 'pending' THEN
    RAISE EXCEPTION 'Submission % is not pending (is %)', submission_id, v_sub_req.status;
  END IF;

  -- Reuse the one blessed grant path: writes the subscriptions ledger AND
  -- extends users.premium_until with the stacking (greatest) logic.
  v_sub := public.grant_subscription(
    v_sub_req.user_id,
    v_sub_req.plan_code,
    v_sub_req.method_label,                                  -- payment_ref
    'Approved payment submission #' || submission_id        -- note
  );

  -- Link the screenshot to the ledger row for the audit trail.
  UPDATE public.subscriptions
     SET payment_proof_path = v_sub_req.proof_path
   WHERE id = v_sub.id;

  UPDATE public.payment_submissions
     SET status          = 'approved',
         subscription_id = v_sub.id,
         reviewed_by     = auth.uid(),
         reviewed_at     = now()
   WHERE id = submission_id;

  RETURN v_sub;
END;
$$;

ALTER FUNCTION "public"."approve_payment_submission"(bigint) OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."reject_payment_submission"(
    "submission_id" bigint,
    "reason" text
)
    RETURNS "public"."payment_submissions"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET search_path = public
    AS $$
DECLARE
  v_row public.payment_submissions;
BEGIN
  UPDATE public.payment_submissions
     SET status        = 'rejected',
         reject_reason = reason,
         reviewed_by   = auth.uid(),
         reviewed_at   = now()
   WHERE id = submission_id AND status = 'pending'
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Submission % not found or not pending', submission_id;
  END IF;

  RETURN v_row;
END;
$$;

ALTER FUNCTION "public"."reject_payment_submission"(bigint, text) OWNER TO "postgres";

-- ---------------------------------------------------------------------------
-- 4. RLS
-- ---------------------------------------------------------------------------
ALTER TABLE "public"."payment_methods"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payment_submissions" ENABLE ROW LEVEL SECURITY;

-- Methods: authenticated users read only ACTIVE methods (to render the pay
-- screen). No write policy => writes denied for authenticated; admin writes via
-- the service_role key (bypasses RLS).
CREATE POLICY "payment_methods read active"
  ON "public"."payment_methods"
  FOR SELECT TO "authenticated"
  USING (is_active = true);

-- Submissions: a user may READ and INSERT only their own rows. Inserts are
-- forced to 'pending' and may not pre-set review/grant fields. No UPDATE/DELETE
-- policy => the status & premium can never be moved from the client.
CREATE POLICY "payment_submissions select own"
  ON "public"."payment_submissions"
  FOR SELECT TO "authenticated"
  USING (
    user_id IN (SELECT id FROM public.users WHERE user_id = auth.uid())
  );

CREATE POLICY "payment_submissions insert own"
  ON "public"."payment_submissions"
  FOR INSERT TO "authenticated"
  WITH CHECK (
    user_id IN (SELECT id FROM public.users WHERE user_id = auth.uid())
    AND status = 'pending'
    AND subscription_id IS NULL
    AND reviewed_by IS NULL
    AND reviewed_at IS NULL
    AND reject_reason IS NULL
  );

-- ---------------------------------------------------------------------------
-- 5. Grants (RLS still filters rows for authenticated).
-- ---------------------------------------------------------------------------
GRANT SELECT                 ON TABLE "public"."payment_methods"     TO "authenticated";
GRANT ALL                    ON TABLE "public"."payment_methods"     TO "service_role";
GRANT SELECT, INSERT         ON TABLE "public"."payment_submissions" TO "authenticated";
GRANT ALL                    ON TABLE "public"."payment_submissions" TO "service_role";

-- RPCs are backend-only (SECURITY DEFINER bypasses RLS).
REVOKE ALL ON FUNCTION "public"."approve_payment_submission"(bigint)       FROM PUBLIC, "anon", "authenticated";
GRANT EXECUTE ON FUNCTION "public"."approve_payment_submission"(bigint)    TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_payment_submission"(bigint, text)  FROM PUBLIC, "anon", "authenticated";
GRANT EXECUTE ON FUNCTION "public"."reject_payment_submission"(bigint, text) TO "service_role";

-- ---------------------------------------------------------------------------
-- 6. Private bucket for receipt screenshots.
--    Path: {auth.uid()}/{uuid}.<ext>  — uid-first folder isolates per user.
--    Admin reads everything via the service_role key (bypasses storage RLS).
-- ---------------------------------------------------------------------------
INSERT INTO "storage"."buckets" ("id", "name", "public")
VALUES ('payment-proofs', 'payment-proofs', false)
ON CONFLICT ("id") DO NOTHING;

DROP POLICY IF EXISTS "own payment proofs" ON "storage"."objects";
CREATE POLICY "own payment proofs" ON "storage"."objects"
  FOR ALL TO "authenticated"
  USING      ("bucket_id" = 'payment-proofs'
              AND (storage.foldername("name"))[1] = auth.uid()::text)
  WITH CHECK ("bucket_id" = 'payment-proofs'
              AND (storage.foldername("name"))[1] = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- 7. Realtime — let the mobile app react live to an approval.
--    users: the app listens to its own row's premium_until flip.
--    payment_submissions: the app also gets status/reject_reason live.
--    (Guarded so re-running the migration won't error.)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'users'
  ) THEN
    ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."users";
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'payment_submissions'
  ) THEN
    ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."payment_submissions";
  END IF;
END $$;
