-- Listening & Shadowing — move user data off the mobile app's local Drift DB
-- into Supabase, so a future web app shares the same account state.
--
-- Net-new here: a per-video free flag, and three user-data tables that were
-- previously local-only (Drift): per-step progress, MCQ practice answers, and
-- voice recordings. Premium is ALREADY handled (users.premium_until +
-- subscriptions); this migration does NOT touch entitlement, only adds is_free.
--
-- Conventions mirrored from 20260607120000_subscriptions.sql:
--   * user rows are keyed by public.users.id (bigint); auth link is users.user_id (uuid)
--   * RLS: a client sees only rows where user_id maps to their auth.uid()

-- ---------------------------------------------------------------------
-- 1. Per-video free flag. Subtitle play is free on every video; the other
--    features unlock when is_free = true OR the user is premium (the app
--    reads the derived is_premium_user from get_user). Flip the sampler set.
-- ---------------------------------------------------------------------
ALTER TABLE "public"."listenings"
    ADD COLUMN IF NOT EXISTS "is_free" boolean NOT NULL DEFAULT false;

-- e.g. free sampler:
-- UPDATE "public"."listenings" SET "is_free" = true WHERE "id" IN (1, 2, 3);


-- ---------------------------------------------------------------------
-- 2. Per-step progress (was Drift VideoStepProgressTable).
--    step_key ∈ subtitle | sentence_explanation | shadowing | speech | mcq
--    state: 0 not started · 1 in progress · 2 completed
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."listening_video_progress" (
    "user_id"        bigint  NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "listening_id"   integer NOT NULL REFERENCES "public"."listenings"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "step_key"       text    NOT NULL,
    "state"          integer NOT NULL DEFAULT 0,
    "open_count"     integer NOT NULL DEFAULT 0,
    "last_opened_at" timestamp with time zone,
    "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_id", "listening_id", "step_key")
);
ALTER TABLE "public"."listening_video_progress" OWNER TO "postgres";


-- ---------------------------------------------------------------------
-- 3. MCQ practice answers (was Drift ListeningPracticeAnswerTable).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."listening_practice_answers" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint  NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "listening_id" integer NOT NULL REFERENCES "public"."listenings"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "group_id"     text    NOT NULL,
    "question_id"  integer NOT NULL,
    "user_answer"  text,
    "time_spent"   integer NOT NULL,
    "is_correct"   boolean NOT NULL,
    "created_at"   timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."listening_practice_answers" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "lpa_user_video_idx"
    ON "public"."listening_practice_answers" ("user_id", "listening_id");


-- ---------------------------------------------------------------------
-- 4. Voice recordings (was Drift UserRecordedSentenceAudioTable + phone file).
--    Audio file goes to the private Storage bucket below; this row holds the
--    metadata + retention. Default keep = 30 days; pinned rows never expire.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."listening_recordings" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint  NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "listening_id" integer NOT NULL REFERENCES "public"."listenings"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "sentence_id"  text    NOT NULL,
    "audio_path"   text    NOT NULL,                                   -- Storage object path
    "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
    "expires_at"   timestamp with time zone NOT NULL DEFAULT (now() + interval '30 days'),
    "pinned"       boolean NOT NULL DEFAULT false
);
ALTER TABLE "public"."listening_recordings" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "rec_user_video_idx"
    ON "public"."listening_recordings" ("user_id", "listening_id");
CREATE INDEX IF NOT EXISTS "rec_expiry_idx"
    ON "public"."listening_recordings" ("expires_at") WHERE NOT "pinned";


-- ---------------------------------------------------------------------
-- 5. RLS — each user reads/writes only their own rows (auth.uid() → users.id).
-- ---------------------------------------------------------------------
ALTER TABLE "public"."listening_video_progress"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listening_practice_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."listening_recordings"       ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own progress" ON "public"."listening_video_progress"
  FOR ALL TO "authenticated"
  USING      ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()))
  WITH CHECK ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

CREATE POLICY "own answers" ON "public"."listening_practice_answers"
  FOR ALL TO "authenticated"
  USING      ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()))
  WITH CHECK ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

CREATE POLICY "own recordings" ON "public"."listening_recordings"
  FOR ALL TO "authenticated"
  USING      ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()))
  WITH CHECK ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."listening_video_progress"   TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."listening_practice_answers" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."listening_recordings"       TO "authenticated";
GRANT ALL ON TABLE "public"."listening_video_progress"   TO "service_role";
GRANT ALL ON TABLE "public"."listening_practice_answers" TO "service_role";
GRANT ALL ON TABLE "public"."listening_recordings"       TO "service_role";


-- ---------------------------------------------------------------------
-- 6. Private Storage bucket for recordings.
--    Object path convention: {auth.uid()}/{listening_id}/{uuid}.m4a
--    (path is keyed by the auth uuid so the storage policy can match it).
-- ---------------------------------------------------------------------
INSERT INTO "storage"."buckets" ("id", "name", "public")
VALUES ('listening-recordings', 'listening-recordings', false)
ON CONFLICT ("id") DO NOTHING;

CREATE POLICY "own recording files" ON "storage"."objects"
  FOR ALL TO "authenticated"
  USING      ("bucket_id" = 'listening-recordings'
              AND (storage.foldername("name"))[1] = auth.uid()::text)
  WITH CHECK ("bucket_id" = 'listening-recordings'
              AND (storage.foldername("name"))[1] = auth.uid()::text);


-- ---------------------------------------------------------------------
-- 7. Retention: purge expired, non-pinned recordings (rows + Storage files).
--    Enable pg_cron and uncomment, or run this body from a scheduled Edge Fn.
-- ---------------------------------------------------------------------
-- SELECT cron.schedule('purge-expired-recordings', '0 3 * * *', $$
--   WITH gone AS (
--     DELETE FROM public.listening_recordings
--     WHERE expires_at < now() AND NOT pinned
--     RETURNING audio_path
--   )
--   DELETE FROM storage.objects
--   WHERE bucket_id = 'listening-recordings'
--     AND name IN (SELECT audio_path FROM gone);
-- $$);
