-- Daily Speaking sessions — server-side record of each AI feedback, so the
-- per-day quota (free 1/day, premium = daily token grant) is enforced where the
-- client can't cheat, and history is web-ready (replaces the local Drift
-- daily_speaking_session_table). Written by the daily-speaking-review edge
-- function (service_role); read by the app via RLS.

CREATE TABLE IF NOT EXISTS "public"."daily_speaking_sessions" (
  "id"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"       bigint NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  "on_ramp"       text   NOT NULL,
  "input_mode"    text   NOT NULL,           -- voice | text
  "topic_id"      text,
  "topic"         jsonb,
  "input_text"    text,                       -- transcript (voice) or typed text
  "feedback"      jsonb  NOT NULL,            -- the DailySpeakingFeedback payload
  "total_tokens"  int    NOT NULL DEFAULT 0,  -- Gemini usage for this call
  "created_at"    timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "public"."daily_speaking_sessions" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "dss_user_created_idx"
  ON "public"."daily_speaking_sessions" ("user_id", "created_at" DESC);

ALTER TABLE "public"."daily_speaking_sessions" ENABLE ROW LEVEL SECURITY;

-- Read own history. Writes happen only via the edge function (service_role),
-- so there is intentionally no INSERT policy for end users.
CREATE POLICY "read own sessions" ON "public"."daily_speaking_sessions"
  FOR SELECT TO "authenticated"
  USING ("user_id" IN (SELECT "id" FROM "public"."users" WHERE "user_id" = auth.uid()));

GRANT SELECT ON "public"."daily_speaking_sessions" TO "authenticated";
GRANT ALL ON "public"."daily_speaking_sessions" TO "service_role";

-- Today's usage for one user (the edge function reads this to apply the quota).
-- date is in UTC; good enough for a daily reset.
CREATE OR REPLACE FUNCTION "public"."daily_speaking_usage_today"("p_user_id" bigint)
    RETURNS TABLE("session_count" int, "tokens_used" int)
    LANGUAGE "sql" STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT count(*)::int,
         coalesce(sum(total_tokens), 0)::int
  FROM public.daily_speaking_sessions
  WHERE user_id = p_user_id
    AND created_at >= date_trunc('day', now());
$$;
ALTER FUNCTION "public"."daily_speaking_usage_today"(bigint) OWNER TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."daily_speaking_usage_today"(bigint) TO "service_role";
