-- Subscriptions & plans (manual admin activation)
-- Free vs premium is derived from users.premium_until (denormalized cache).
-- Source of truth = public.subscriptions (one row per manual grant).

-- 1. Rename the legacy premium cache column for clarity.
--    get_user already drives is_premium_user off this column; mobile only ever
--    reads the derived boolean, so renaming is safe.
ALTER TABLE "public"."users" RENAME COLUMN "expired_at" TO "premium_until";

-- 2. Plan catalog (managed from the admin; prices in minor units, e.g. MMK).
CREATE TABLE IF NOT EXISTS "public"."subscription_plans" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" text NOT NULL UNIQUE,                       -- 'monthly' | '6_month' | '12_month'
    "name" text NOT NULL,
    "duration_days" integer NOT NULL,
    "price_cents" integer NOT NULL DEFAULT 0,
    "currency" text NOT NULL DEFAULT 'MMK',
    "daily_token_grant" integer NOT NULL DEFAULT 72000,   -- credit-entitlement: premium grant
    "max_recording_seconds" integer NOT NULL DEFAULT 300, -- 5 min premium
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."subscription_plans" OWNER TO "postgres";

-- 3. Subscription ledger. One row per grant; doubles as purchase history.
CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint NOT NULL REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "plan_id" bigint NOT NULL REFERENCES "public"."subscription_plans"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "status" text NOT NULL DEFAULT 'active',          -- active | expired | refunded | trialing
    "started_at" timestamp with time zone NOT NULL DEFAULT now(),
    "current_period_end" timestamp with time zone NOT NULL,
    "provider" text NOT NULL DEFAULT 'manual',        -- manual | play | apple | stripe (future)
    "payment_ref" text,                               -- bank / KBZPay / Wave reference
    "payment_proof_path" text,                        -- optional screenshot (private bucket)
    "granted_by" uuid,                                -- admin auth.uid() when available
    "note" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."subscriptions" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "subscriptions_user_id_idx" ON "public"."subscriptions" ("user_id");
CREATE INDEX IF NOT EXISTS "subscriptions_status_idx" ON "public"."subscriptions" ("status");

-- 4. Seed the three plans. Fill in real prices via the admin / an UPDATE.
INSERT INTO "public"."subscription_plans" ("code", "name", "duration_days", "price_cents")
VALUES
    ('monthly',  'Monthly',   30,  0),
    ('6_month',  '6 Months',  182, 0),
    ('12_month', '12 Months', 365, 0)
ON CONFLICT ("code") DO NOTHING;

-- 5. Recreate get_user to read premium_until (same return signature as before so
--    the mobile AppUser deserialization is untouched). Also fixes the previous
--    NULL-handling: a user with no premium_until is now correctly Free.
CREATE OR REPLACE FUNCTION "public"."get_user"("user_id_param" "uuid")
    RETURNS TABLE("id" bigint, "name" "text", "email" "text", "profile_path" "text", "user_id" "uuid", "device_id" "text", "total_token_used" bigint, "is_premium_user" boolean)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT
    users.id,
    users.name,
    users.email,
    users.profile_path,
    users.user_id,
    users.device_id,
    users.total_token_used,
    (users.premium_until IS NOT NULL AND users.premium_until > now()) AS is_premium_user
  FROM
    users
  WHERE users.user_id = user_id_param;
END;
$$;

ALTER FUNCTION "public"."get_user"("user_id_param" "uuid") OWNER TO "postgres";

-- 6. The one admin entry point. Inserts a subscription row and extends the cache.
--    greatest(now, premium_until) makes early renewals STACK remaining days
--    instead of overwriting. Handles all plan lengths via plan_code.
CREATE OR REPLACE FUNCTION "public"."grant_subscription"(
    "target_user_id" bigint,
    "plan_code" text,
    "payment_ref_param" text DEFAULT NULL,
    "note_param" text DEFAULT NULL
)
    RETURNS "public"."subscriptions"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET search_path = public
    AS $$
DECLARE
  v_plan   public.subscription_plans;
  v_base   timestamp with time zone;
  v_end    timestamp with time zone;
  v_sub    public.subscriptions;
BEGIN
  SELECT * INTO v_plan
  FROM public.subscription_plans
  WHERE code = plan_code AND is_active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown or inactive plan: %', plan_code;
  END IF;

  SELECT greatest(now(), coalesce(premium_until, now())) INTO v_base
  FROM public.users
  WHERE id = target_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown user: %', target_user_id;
  END IF;

  v_end := v_base + make_interval(days => v_plan.duration_days);

  INSERT INTO public.subscriptions
    (user_id, plan_id, status, current_period_end, provider, payment_ref, granted_by, note)
  VALUES
    (target_user_id, v_plan.id, 'active', v_end, 'manual', payment_ref_param, auth.uid(), note_param)
  RETURNING * INTO v_sub;

  UPDATE public.users SET premium_until = v_end WHERE id = target_user_id;

  RETURN v_sub;
END;
$$;

ALTER FUNCTION "public"."grant_subscription"(bigint, text, text, text) OWNER TO "postgres";

-- 7. Optional maintenance: flip lapsed rows to 'expired' for clean reporting.
--    Premium access itself never depends on this (it's the live premium_until
--    check). Schedule via pg_cron if desired:
--      select cron.schedule('expire-subs','5 0 * * *',$$select public.expire_subscriptions()$$);
CREATE OR REPLACE FUNCTION "public"."expire_subscriptions"()
    RETURNS integer
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET search_path = public
    AS $$
DECLARE
  v_count integer;
BEGIN
  UPDATE public.subscriptions
  SET status = 'expired'
  WHERE status IN ('active','trialing')
    AND current_period_end < now();
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

ALTER FUNCTION "public"."expire_subscriptions"() OWNER TO "postgres";

-- 8. RLS — money tables are NOT client-writable.
ALTER TABLE "public"."subscription_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;

-- Plans: any authenticated user may read the catalog (to show prices). No
-- write policy => writes denied for authenticated; service_role bypasses RLS.
CREATE POLICY "plans readable by authenticated"
  ON "public"."subscription_plans"
  FOR SELECT TO "authenticated"
  USING (true);

-- Subscriptions: a user may read ONLY their own rows. No insert/update/delete
-- policy => clients can never self-grant premium. All writes go through
-- grant_subscription (service_role) or the admin (service_role key).
CREATE POLICY "subscriptions select own"
  ON "public"."subscriptions"
  FOR SELECT TO "authenticated"
  USING (
    user_id IN (SELECT id FROM public.users WHERE user_id = auth.uid())
  );

-- 9. Grants. Table-level privileges (RLS still filters rows).
GRANT SELECT ON TABLE "public"."subscription_plans" TO "authenticated", "anon";
GRANT ALL    ON TABLE "public"."subscription_plans" TO "service_role";
GRANT SELECT ON TABLE "public"."subscriptions"      TO "authenticated";
GRANT ALL    ON TABLE "public"."subscriptions"      TO "service_role";

-- grant_subscription must be callable ONLY by the backend (service_role) — never
-- by end users, since SECURITY DEFINER bypasses RLS.
REVOKE ALL ON FUNCTION "public"."grant_subscription"(bigint, text, text, text) FROM PUBLIC, "anon", "authenticated";
GRANT EXECUTE ON FUNCTION "public"."grant_subscription"(bigint, text, text, text) TO "service_role";

REVOKE ALL ON FUNCTION "public"."expire_subscriptions"() FROM PUBLIC, "anon", "authenticated";
GRANT EXECUTE ON FUNCTION "public"."expire_subscriptions"() TO "service_role";
