

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_translations_with_vocabularies_by_day"("translation_day_id_param" integer) RETURNS TABLE("id" bigint, "burmese_text" "text", "english_text" "text", "words" "text", "day_id" bigint, "vocabularies" "jsonb")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT 
    t.id,
    t.burmese_text,
    t.english_text,
    t.words,
    t.translation_day_id,
    COALESCE(
      JSON_AGG(
        JSON_BUILD_OBJECT(
          'id', pv.id,
          'english_text', pv.english_text,
          'burmese_text', pv.burmese_text,
          'audio_path', pv.audio_path
        )
      ) FILTER (WHERE pv.id IS NOT NULL)::JSONB,
      '[]'::JSONB
    ) AS vocabularies
  FROM 
    translations t
  LEFT JOIN 
    translation_vocabulary_relation tvr ON t.id = tvr.translation_id
  LEFT JOIN 
    pattern_vocabularies pv ON tvr.vocabulary_id = pv.id
  WHERE 
    t.translation_day_id = translation_day_id_param
  GROUP BY 
    t.id, t.burmese_text, t.english_text
  ORDER BY 
    t.id;
END;
$$;


ALTER FUNCTION "public"."get_translations_with_vocabularies_by_day"("translation_day_id_param" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_user"("user_id_param" "uuid") RETURNS TABLE("id" bigint, "name" "text", "email" "text", "profile_path" "text", "user_id" "uuid", "device_id" "text", "total_token_used" bigint, "is_premium_user" boolean)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT
    users.id,
    users.name,
    users.email,
    users.profile_path,
    users.user_id,
    users.device_id,
    users.total_token_used,
    CASE
      WHEN users.expired_at < CURRENT_DATE THEN false
      ELSE true
    END AS is_premium_user
  FROM
    users
  WHERE users.user_id = user_id_param;
END;
$$;


ALTER FUNCTION "public"."get_user"("user_id_param" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_versions" (
    "id" bigint NOT NULL,
    "version_name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "build_number" bigint NOT NULL,
    "app_path" "text" NOT NULL,
    "force_update" boolean DEFAULT false NOT NULL,
    "audio_path" "text",
    "telegram_path" "text"
);


ALTER TABLE "public"."app_versions" OWNER TO "postgres";


ALTER TABLE "public"."app_versions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_versions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."days" (
    "id" bigint NOT NULL,
    "order_number" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."days" OWNER TO "postgres";


ALTER TABLE "public"."days" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."days_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."days_users_relation" (
    "day_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."days_users_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."exercise_user_answers" (
    "id" bigint NOT NULL,
    "answer" "text" NOT NULL,
    "pattern_exercise_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."exercise_user_answers" OWNER TO "postgres";


ALTER TABLE "public"."exercise_user_answers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exercise_user_answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exercises" (
    "id" bigint NOT NULL,
    "exercise_name" "text" NOT NULL,
    "day_id" bigint NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."exercises" OWNER TO "postgres";


ALTER TABLE "public"."exercises" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exercises_users_relation" (
    "exercise_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."exercises_users_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lessons" (
    "id" bigint NOT NULL,
    "lesson_name" "text" NOT NULL,
    "day_id" bigint NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "subtitle" "text"
);


ALTER TABLE "public"."lessons" OWNER TO "postgres";


ALTER TABLE "public"."lessons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."lessons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listening_categories" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."listening_categories" OWNER TO "postgres";


ALTER TABLE "public"."listening_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listening_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listening_vocabularies" (
    "id" bigint NOT NULL,
    "english_text" "text" NOT NULL,
    "burmese_text" "text",
    "description" "text",
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."listening_vocabularies" OWNER TO "postgres";


ALTER TABLE "public"."listening_vocabularies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listening_vocabularies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listening_vocabularies_relation" (
    "listening_id" integer NOT NULL,
    "vocabulary_id" bigint NOT NULL
);


ALTER TABLE "public"."listening_vocabularies_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."listenings" (
    "id" integer NOT NULL,
    "title" "text" NOT NULL,
    "thumbnail" "text",
    "youtube_id" "text" NOT NULL,
    "subtitle_path" "text" NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "listening_category_id" integer,
    "start" bigint NOT NULL,
    "end" bigint NOT NULL,
    "mm_subtitle" boolean DEFAULT false NOT NULL,
    "has_vocabularies" boolean DEFAULT false NOT NULL,
    "shadowing_path" "text" NOT NULL,
    "multiple_choice_path" "text" NOT NULL,
    "record_subtitle_path" "text" NOT NULL,
    "sentence_explanation_path" "text" DEFAULT ''::"text" NOT NULL,
    "order_number" integer DEFAULT 0 NOT NULL,
    "vocabulary_path" "text" DEFAULT ''::"text" NOT NULL,
    "is_published" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."listenings" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."listenings_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."listenings_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."listenings_id_seq" OWNED BY "public"."listenings"."id";



CREATE TABLE IF NOT EXISTS "public"."love_user_comments" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "pattern_user_comment_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."love_user_comments" OWNER TO "postgres";


ALTER TABLE "public"."love_user_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."love_user_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pattern_examples" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "english_text" "text" NOT NULL,
    "burmese_text" "text",
    "pattern_id" bigint NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "start_at" bigint,
    "audio_url" "text",
    "practicable" boolean DEFAULT false NOT NULL,
    "words" "text",
    "explanation" "text"
);


ALTER TABLE "public"."pattern_examples" OWNER TO "postgres";


ALTER TABLE "public"."pattern_examples" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pattern_examples_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pattern_examples_vocabularies_relation" (
    "pattern_example_id" bigint NOT NULL,
    "vocabulary_id" bigint NOT NULL
);


ALTER TABLE "public"."pattern_examples_vocabularies_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pattern_exercises" (
    "id" bigint NOT NULL,
    "burmese_text" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "english_text" "text" NOT NULL,
    "pattern_id" bigint,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "exercise_id" bigint NOT NULL,
    "audio_path" "text",
    "words" "text"
);


ALTER TABLE "public"."pattern_exercises" OWNER TO "postgres";


ALTER TABLE "public"."pattern_exercises" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pattern_exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pattern_exercises_vocabularies_relation" (
    "vocabulary_id" bigint NOT NULL,
    "pattern_exercise_id" bigint NOT NULL
);


ALTER TABLE "public"."pattern_exercises_vocabularies_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pattern_user_comments" (
    "id" bigint NOT NULL,
    "comment" "text" NOT NULL,
    "user_id" bigint NOT NULL,
    "pattern_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."pattern_user_comments" OWNER TO "postgres";


ALTER TABLE "public"."pattern_user_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pattern_user_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pattern_vocabularies" (
    "id" bigint NOT NULL,
    "english_text" "text" NOT NULL,
    "burmese_text" "text",
    "audio_path" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."pattern_vocabularies" OWNER TO "postgres";


ALTER TABLE "public"."pattern_vocabularies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pattern_vocabularies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pattern_vocabulary_relation" (
    "pattern_id" bigint NOT NULL,
    "vocabulary_id" bigint NOT NULL
);


ALTER TABLE "public"."pattern_vocabulary_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."patterns" (
    "id" bigint NOT NULL,
    "pattern" "text" NOT NULL,
    "title" "text",
    "description" "text",
    "audio_path" "text",
    "lesson_id" bigint,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "svg_audio_path" "text",
    "self_practicable" boolean DEFAULT true NOT NULL,
    "svg" "jsonb",
    "svg_id" bigint,
    "file_path" "text" DEFAULT ''::"text" NOT NULL,
    "order_number" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."patterns" OWNER TO "postgres";


ALTER TABLE "public"."patterns" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."patterns_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."premium_users" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "expired_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."premium_users" OWNER TO "postgres";


ALTER TABLE "public"."premium_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."premium_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subject_verb_agreements" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "svg_data" "jsonb" NOT NULL
);


ALTER TABLE "public"."subject_verb_agreements" OWNER TO "postgres";


ALTER TABLE "public"."subject_verb_agreements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subject_verb_agreement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."translation_days" (
    "id" bigint NOT NULL,
    "day_name" "text" NOT NULL,
    "translation_level_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."translation_days" OWNER TO "postgres";


ALTER TABLE "public"."translation_days" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."translation_days_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."translation_days_users_relation" (
    "translation_day_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."translation_days_users_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."translation_levels" (
    "id" bigint NOT NULL,
    "level_name" "text" NOT NULL,
    "is_deleted" "text" DEFAULT 'false'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."translation_levels" OWNER TO "postgres";


ALTER TABLE "public"."translation_levels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."translation_levels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."translation_user_answer" (
    "id" bigint NOT NULL,
    "answer" "text" NOT NULL,
    "user_id" bigint NOT NULL,
    "translation_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."translation_user_answer" OWNER TO "postgres";


ALTER TABLE "public"."translation_user_answer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."translation_user_answer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."translation_vocabulary_relation" (
    "translation_id" bigint NOT NULL,
    "vocabulary_id" bigint NOT NULL
);


ALTER TABLE "public"."translation_vocabulary_relation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."translations" (
    "id" bigint NOT NULL,
    "english_text" "text" NOT NULL,
    "burmese_text" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "translation_day_id" bigint NOT NULL,
    "words" "text",
    "audio_path" "text"
);


ALTER TABLE "public"."translations" OWNER TO "postgres";


ALTER TABLE "public"."translations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."translations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_comment_replies" (
    "id" bigint NOT NULL,
    "reply" "text" NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pattern_user_comment_id" bigint
);


ALTER TABLE "public"."user_comment_replies" OWNER TO "postgres";


ALTER TABLE "public"."user_comment_replies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_comment_replies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "name" "text",
    "email" "text" NOT NULL,
    "profile_path" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "account_id" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_type" "text" DEFAULT 'student'::"text" NOT NULL,
    "device_id" "text",
    "expired_at" timestamp with time zone,
    "total_token_used" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."listenings" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."listenings_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."app_versions"
    ADD CONSTRAINT "app_versions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."days"
    ADD CONSTRAINT "days_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."days_users_relation"
    ADD CONSTRAINT "days_users_relation_pkey" PRIMARY KEY ("day_id", "user_id");



ALTER TABLE ONLY "public"."exercise_user_answers"
    ADD CONSTRAINT "exercise_user_answers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exercises"
    ADD CONSTRAINT "exercises_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exercises_users_relation"
    ADD CONSTRAINT "exercises_users_relation_pkey" PRIMARY KEY ("exercise_id", "user_id");



ALTER TABLE ONLY "public"."lessons"
    ADD CONSTRAINT "lessons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listening_categories"
    ADD CONSTRAINT "listening_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listening_vocabularies"
    ADD CONSTRAINT "listening_vocabularies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listening_vocabularies_relation"
    ADD CONSTRAINT "listening_vocabulary_relation_pkey" PRIMARY KEY ("listening_id", "vocabulary_id");



ALTER TABLE ONLY "public"."listenings"
    ADD CONSTRAINT "listenings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."love_user_comments"
    ADD CONSTRAINT "love_user_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pattern_examples"
    ADD CONSTRAINT "pattern_examples_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pattern_examples_vocabularies_relation"
    ADD CONSTRAINT "pattern_examples_vocabularies_relation_pkey" PRIMARY KEY ("pattern_example_id", "vocabulary_id");



ALTER TABLE ONLY "public"."pattern_exercises"
    ADD CONSTRAINT "pattern_exercises_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pattern_exercises_vocabularies_relation"
    ADD CONSTRAINT "pattern_exercises_vocabularies_relation_pkey" PRIMARY KEY ("vocabulary_id", "pattern_exercise_id");



ALTER TABLE ONLY "public"."pattern_user_comments"
    ADD CONSTRAINT "pattern_user_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pattern_vocabularies"
    ADD CONSTRAINT "pattern_vocabularies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pattern_vocabulary_relation"
    ADD CONSTRAINT "pattern_vocabulary_relation_pkey" PRIMARY KEY ("pattern_id", "vocabulary_id");



ALTER TABLE ONLY "public"."patterns"
    ADD CONSTRAINT "patterns_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."premium_users"
    ADD CONSTRAINT "premium_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subject_verb_agreements"
    ADD CONSTRAINT "subject_verb_agreement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."translation_days"
    ADD CONSTRAINT "translation_days_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."translation_days_users_relation"
    ADD CONSTRAINT "translation_days_users_relation_pkey" PRIMARY KEY ("translation_day_id", "user_id");



ALTER TABLE ONLY "public"."translation_levels"
    ADD CONSTRAINT "translation_levels_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."translation_user_answer"
    ADD CONSTRAINT "translation_user_answer_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."translation_vocabulary_relation"
    ADD CONSTRAINT "translation_vocabulary_relation_pkey" PRIMARY KEY ("translation_id", "vocabulary_id");



ALTER TABLE ONLY "public"."translations"
    ADD CONSTRAINT "translations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_comment_replies"
    ADD CONSTRAINT "user_comment_replies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."days_users_relation"
    ADD CONSTRAINT "days_users_relation_day_id_fkey" FOREIGN KEY ("day_id") REFERENCES "public"."days"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."days_users_relation"
    ADD CONSTRAINT "days_users_relation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercise_user_answers"
    ADD CONSTRAINT "exercise_user_answers_pattern_exercise_id_fkey" FOREIGN KEY ("pattern_exercise_id") REFERENCES "public"."pattern_exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercise_user_answers"
    ADD CONSTRAINT "exercise_user_answers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercises"
    ADD CONSTRAINT "exercises_day_id_fkey" FOREIGN KEY ("day_id") REFERENCES "public"."days"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercises_users_relation"
    ADD CONSTRAINT "exercises_users_relation_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercises_users_relation"
    ADD CONSTRAINT "exercises_users_relation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."lessons"
    ADD CONSTRAINT "lessons_day_id_fkey" FOREIGN KEY ("day_id") REFERENCES "public"."days"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."listening_vocabularies_relation"
    ADD CONSTRAINT "listening_vocabularies_relation_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "public"."pattern_vocabularies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."listening_vocabularies_relation"
    ADD CONSTRAINT "listening_vocabulary_relation_listening_id_fkey" FOREIGN KEY ("listening_id") REFERENCES "public"."listenings"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."listenings"
    ADD CONSTRAINT "listenings_listening_category_id_fkey" FOREIGN KEY ("listening_category_id") REFERENCES "public"."listening_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."love_user_comments"
    ADD CONSTRAINT "love_user_comments_pattern_user_comment_id_fkey" FOREIGN KEY ("pattern_user_comment_id") REFERENCES "public"."pattern_user_comments"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."love_user_comments"
    ADD CONSTRAINT "love_user_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_examples"
    ADD CONSTRAINT "pattern_examples_pattern_id_fkey" FOREIGN KEY ("pattern_id") REFERENCES "public"."patterns"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_examples_vocabularies_relation"
    ADD CONSTRAINT "pattern_examples_vocabularies_relation_pattern_example_id_fkey" FOREIGN KEY ("pattern_example_id") REFERENCES "public"."pattern_examples"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_examples_vocabularies_relation"
    ADD CONSTRAINT "pattern_examples_vocabularies_relation_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "public"."pattern_vocabularies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_exercises"
    ADD CONSTRAINT "pattern_exercises_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_exercises"
    ADD CONSTRAINT "pattern_exercises_pattern_id_fkey" FOREIGN KEY ("pattern_id") REFERENCES "public"."patterns"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_exercises_vocabularies_relation"
    ADD CONSTRAINT "pattern_exercises_vocabularies_relatio_pattern_exercise_id_fkey" FOREIGN KEY ("pattern_exercise_id") REFERENCES "public"."pattern_exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_exercises_vocabularies_relation"
    ADD CONSTRAINT "pattern_exercises_vocabularies_relation_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "public"."pattern_vocabularies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_user_comments"
    ADD CONSTRAINT "pattern_user_comments_pattern_id_fkey" FOREIGN KEY ("pattern_id") REFERENCES "public"."patterns"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_user_comments"
    ADD CONSTRAINT "pattern_user_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_vocabulary_relation"
    ADD CONSTRAINT "pattern_vocabulary_relation_pattern_id_fkey" FOREIGN KEY ("pattern_id") REFERENCES "public"."patterns"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pattern_vocabulary_relation"
    ADD CONSTRAINT "pattern_vocabulary_relation_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "public"."pattern_vocabularies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."patterns"
    ADD CONSTRAINT "patterns_svg_id_fkey" FOREIGN KEY ("svg_id") REFERENCES "public"."subject_verb_agreements"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."premium_users"
    ADD CONSTRAINT "premium_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_days"
    ADD CONSTRAINT "translation_days_translation_level_id_fkey" FOREIGN KEY ("translation_level_id") REFERENCES "public"."translation_levels"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_days_users_relation"
    ADD CONSTRAINT "translation_days_users_relation_translation_day_id_fkey" FOREIGN KEY ("translation_day_id") REFERENCES "public"."translation_days"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_days_users_relation"
    ADD CONSTRAINT "translation_days_users_relation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_user_answer"
    ADD CONSTRAINT "translation_user_answer_translation_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "public"."translations"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_user_answer"
    ADD CONSTRAINT "translation_user_answer_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_vocabulary_relation"
    ADD CONSTRAINT "translation_vocabulary_relation_translation_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "public"."translations"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translation_vocabulary_relation"
    ADD CONSTRAINT "translation_vocabulary_relation_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "public"."pattern_vocabularies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."translations"
    ADD CONSTRAINT "translations_translation_day_id_fkey" FOREIGN KEY ("translation_day_id") REFERENCES "public"."translation_days"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_comment_replies"
    ADD CONSTRAINT "user_comment_replies_pattern_user_comment_id_fkey" FOREIGN KEY ("pattern_user_comment_id") REFERENCES "public"."pattern_user_comments"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_comment_replies"
    ADD CONSTRAINT "user_comment_replies_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow all access to authenticated users" ON "public"."days" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."days_users_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."exercise_user_answers" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."exercises" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."exercises_users_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."lessons" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."love_user_comments" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_examples" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_exercises" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_exercises_vocabularies_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_user_comments" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_vocabularies" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."pattern_vocabulary_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."patterns" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."premium_users" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translation_days" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translation_days_users_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translation_levels" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translation_user_answer" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translation_vocabulary_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."translations" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."user_comment_replies" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all access to authenticated users" ON "public"."users" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow all access to auth users" ON "public"."pattern_examples_vocabularies_relation" USING (true) WITH CHECK (true);



CREATE POLICY "allow all access to authenticated users" ON "public"."listening_vocabularies" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow all access to authenticated users" ON "public"."listening_vocabularies_relation" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow all access to authenticated users" ON "public"."listenings" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow all access to authenticated users" ON "public"."subject_verb_agreements" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."app_versions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."days" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."days_users_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exercise_user_answers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exercises" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exercises_users_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lessons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listening_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listening_vocabularies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listening_vocabularies_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listenings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."love_user_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_examples" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_examples_vocabularies_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_exercises" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_exercises_vocabularies_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_user_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_vocabularies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pattern_vocabulary_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."patterns" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."premium_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subject_verb_agreements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_days" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_days_users_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_levels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_user_answer" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_vocabulary_relation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_comment_replies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "‌allow all access to authenticated users" ON "public"."app_versions" TO "authenticated" USING (true) WITH CHECK (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";































































































































































GRANT ALL ON FUNCTION "public"."get_translations_with_vocabularies_by_day"("translation_day_id_param" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_translations_with_vocabularies_by_day"("translation_day_id_param" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_translations_with_vocabularies_by_day"("translation_day_id_param" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_user"("user_id_param" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user"("user_id_param" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user"("user_id_param" "uuid") TO "service_role";



























GRANT ALL ON TABLE "public"."app_versions" TO "anon";
GRANT ALL ON TABLE "public"."app_versions" TO "authenticated";
GRANT ALL ON TABLE "public"."app_versions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_versions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_versions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_versions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."days" TO "anon";
GRANT ALL ON TABLE "public"."days" TO "authenticated";
GRANT ALL ON TABLE "public"."days" TO "service_role";



GRANT ALL ON SEQUENCE "public"."days_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."days_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."days_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."days_users_relation" TO "anon";
GRANT ALL ON TABLE "public"."days_users_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."days_users_relation" TO "service_role";



GRANT ALL ON TABLE "public"."exercise_user_answers" TO "anon";
GRANT ALL ON TABLE "public"."exercise_user_answers" TO "authenticated";
GRANT ALL ON TABLE "public"."exercise_user_answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exercise_user_answers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exercise_user_answers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exercise_user_answers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exercises" TO "anon";
GRANT ALL ON TABLE "public"."exercises" TO "authenticated";
GRANT ALL ON TABLE "public"."exercises" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exercises_users_relation" TO "anon";
GRANT ALL ON TABLE "public"."exercises_users_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."exercises_users_relation" TO "service_role";



GRANT ALL ON TABLE "public"."lessons" TO "anon";
GRANT ALL ON TABLE "public"."lessons" TO "authenticated";
GRANT ALL ON TABLE "public"."lessons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lessons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."lessons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lessons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."listening_categories" TO "anon";
GRANT ALL ON TABLE "public"."listening_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."listening_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."listening_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."listening_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."listening_categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."listening_vocabularies" TO "anon";
GRANT ALL ON TABLE "public"."listening_vocabularies" TO "authenticated";
GRANT ALL ON TABLE "public"."listening_vocabularies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."listening_vocabularies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."listening_vocabularies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."listening_vocabularies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."listening_vocabularies_relation" TO "anon";
GRANT ALL ON TABLE "public"."listening_vocabularies_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."listening_vocabularies_relation" TO "service_role";



GRANT ALL ON TABLE "public"."listenings" TO "anon";
GRANT ALL ON TABLE "public"."listenings" TO "authenticated";
GRANT ALL ON TABLE "public"."listenings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."listenings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."listenings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."listenings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."love_user_comments" TO "anon";
GRANT ALL ON TABLE "public"."love_user_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."love_user_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."love_user_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."love_user_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."love_user_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_examples" TO "anon";
GRANT ALL ON TABLE "public"."pattern_examples" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_examples" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pattern_examples_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pattern_examples_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pattern_examples_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_examples_vocabularies_relation" TO "anon";
GRANT ALL ON TABLE "public"."pattern_examples_vocabularies_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_examples_vocabularies_relation" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_exercises" TO "anon";
GRANT ALL ON TABLE "public"."pattern_exercises" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_exercises" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pattern_exercises_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pattern_exercises_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pattern_exercises_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_exercises_vocabularies_relation" TO "anon";
GRANT ALL ON TABLE "public"."pattern_exercises_vocabularies_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_exercises_vocabularies_relation" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_user_comments" TO "anon";
GRANT ALL ON TABLE "public"."pattern_user_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_user_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pattern_user_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pattern_user_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pattern_user_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_vocabularies" TO "anon";
GRANT ALL ON TABLE "public"."pattern_vocabularies" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_vocabularies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pattern_vocabularies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pattern_vocabularies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pattern_vocabularies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pattern_vocabulary_relation" TO "anon";
GRANT ALL ON TABLE "public"."pattern_vocabulary_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."pattern_vocabulary_relation" TO "service_role";



GRANT ALL ON TABLE "public"."patterns" TO "anon";
GRANT ALL ON TABLE "public"."patterns" TO "authenticated";
GRANT ALL ON TABLE "public"."patterns" TO "service_role";



GRANT ALL ON SEQUENCE "public"."patterns_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."patterns_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."patterns_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."premium_users" TO "anon";
GRANT ALL ON TABLE "public"."premium_users" TO "authenticated";
GRANT ALL ON TABLE "public"."premium_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."premium_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."premium_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."premium_users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."subject_verb_agreements" TO "anon";
GRANT ALL ON TABLE "public"."subject_verb_agreements" TO "authenticated";
GRANT ALL ON TABLE "public"."subject_verb_agreements" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subject_verb_agreement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subject_verb_agreement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subject_verb_agreement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."translation_days" TO "anon";
GRANT ALL ON TABLE "public"."translation_days" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_days" TO "service_role";



GRANT ALL ON SEQUENCE "public"."translation_days_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."translation_days_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."translation_days_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."translation_days_users_relation" TO "anon";
GRANT ALL ON TABLE "public"."translation_days_users_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_days_users_relation" TO "service_role";



GRANT ALL ON TABLE "public"."translation_levels" TO "anon";
GRANT ALL ON TABLE "public"."translation_levels" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_levels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."translation_levels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."translation_levels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."translation_levels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."translation_user_answer" TO "anon";
GRANT ALL ON TABLE "public"."translation_user_answer" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_user_answer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."translation_user_answer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."translation_user_answer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."translation_user_answer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."translation_vocabulary_relation" TO "anon";
GRANT ALL ON TABLE "public"."translation_vocabulary_relation" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_vocabulary_relation" TO "service_role";



GRANT ALL ON TABLE "public"."translations" TO "anon";
GRANT ALL ON TABLE "public"."translations" TO "authenticated";
GRANT ALL ON TABLE "public"."translations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."translations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."translations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."translations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_comment_replies" TO "anon";
GRANT ALL ON TABLE "public"."user_comment_replies" TO "authenticated";
GRANT ALL ON TABLE "public"."user_comment_replies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_comment_replies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_comment_replies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_comment_replies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























